greg_core:
    resource: "@GregCoreBundle/Resources/config/routing.yml"
    prefix:   /

greg_platform:
    resource: "@GregPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

greg_core:
    resource: "@GregPlatformBundle/Resources/config/routing.yml";