Greg\PlatformBundle\Entity\Skill:
    type: entity
    table: null
    repositoryClass: Greg\PlatformBundle\Repository\SkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
