<?php

namespace Greg\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
   public function getAdverts()
   {
    $query = $this->createQueryBuilder('a')
        // jointure sur l'attribut image
        ->leftJoin('a.image', 'i')
        ->addSelect('i')
        // jointure sur l'attribut categories
        ->leftJoin('a.categories', 'c')
        ->addSelect('c')
        ->orderBy('a.date', 'DESC')
        ->getQuery();

       // retourne le resultat
       return $query->getResult();
   }
}