<?php

namespace Greg\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
   public function getAdverts($page, $nbPerPage)
   {
    $query = $this->createQueryBuilder('a')
        // jointure sur l'attribut image
        ->leftJoin('a.image', 'i')
        ->addSelect('i')
        // jointure sur l'attribut categories
        ->leftJoin('a.categories', 'c')
        ->addSelect('c')
        ->orderBy('a.date', 'DESC')
        ->getQuery();

       $query
           // à partir de quelle annonce commencer la liste
           ->setFirstResult(($page-1) * $nbPerPage)
           // nombre d'annonce à afficher par page
           ->setMaxResults($nbPerPage);

       // retourne l'objet paginator qui correspond à la requête construite
       return new Paginator($query, true);
   }
}