<?php

namespace Greg\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
   public function getAdvertWithCategories(array $categoryNames)
   {
    $qb = $this->createQueryBuilder('a');
       // jointure avec l'entité Catégory avec pour alia "c"

       $qb
           ->innerJoin('a.categories', 'c')
           ->addSelect('c');

       // filtre sur le nom des catégories
       $qb->where($qb->expr()->in('c.name', $categoryNames));

       // retourne le resultat
       return $qb
           ->getQuery()
           ->getResult();
   }
}