<?php

namespace Greg\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function getApplicationWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('a');

        // jointure avec l'entité advert
        $qb
            ->innerJoin('a.advert', 'adv')
            ->addSelect('adv');

        // retourne $limit resultats
        $qb->setMaxResults($limit);

        // retourne le resultat
        return $qb
            ->getQuery()
            ->getResult();
    }


}
