greg_platform_homepage:
    path:      /{page}
    defaults:
        _controller: GregPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

greg_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: GregPlatformBundle:Advert:view
    requirements:
        id: \d+

greg_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

greg_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

greg_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+